################################################
# Server configurations
################################################
server:
  connector:
    # Changing port is available for embedded server only
    # Is is not possible to change port for deploying application on external server
    port: 8080


################################################
# Application (global) configurations
################################################
application:
  # License path
  # Absolute or relative path to GroupDocs license file
  licensePath:
  # Host name or ip for server instance
  hostAddress:


################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: true
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document download
  # Set false to disable document download
  download: true
  # Document upload
  # Set false to disable document upload
  upload: true
  # Document print
  # Set false to disable document print
  print: true
  # File browser
  # Set false to disable document browse
  browse: true
  # Set false to disable right mouse click
  enableRightClick: true

################################################
# GroupDocs.Annotation configurations
################################################
annotation:
  # Files directory path
  # Absolute or relative path to files directory
  filesDirectory: DocumentSamples
  # Default document
  # Absolute path to default document
  defaultDocument:
  # Pages preload
  # How many pages from a document should be loaded, remaining pages will be loaded on page scrolling
  # Set 0 to load all pages at once
  preloadPageCount: 0
  # Fonts path
  # Absolute path to custom fonts directory
  fontsDirectory:
  # Enable/disable Text annotation
  textAnnotation: true
  # Enable/disable Area annotation
  areaAnnotation: true
  # Enable/disable Point annotation
  pointAnnotation: true
  # Enable/disable TextStrikeout annotation
  textStrikeoutAnnotation: true
  # Enable/disable Polyline annotation
  polylineAnnotation: true
  # Enable/disable TextField annotation
  textFieldAnnotation: true
  # Enable/disable Watermark annotation
  watermarkAnnotation: true
  # Enable/disable TextReplacement annotation
  textReplacementAnnotation: true
  # Enable/disable Arrow annotation
  arrowAnnotation: true
  # Enable/disable TextRedaction annotation
  textRedactionAnnotation: true
  # Enable/disable ResourcesRedaction annotation
  resourcesRedactionAnnotation: true
  # Enable/disable TextUnderline annotation
  textUnderlineAnnotation: true
  # Enable/disable Distance annotation
  distanceAnnotation: true
  # Enable/disable original document downloading
  downloadOriginal: true
  # Enable/disable signed document downloading
  downloadAnnotated: true
  # Enable/disable zoom
  zoom: true
  # Enable/disable fit width
  # set true to zoom document pages fit width
  fitWidth: true
